name: Coverage Report

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 9
      - name: Generate Coverage Report
        run: mvn clean verify
      - name: Archive Jacoco reports
        with:
          name: jacoco-reports
          path: test-coverage/target/site/jacoco-aggregate
